require:
-  rubocop-minitest
-  rubocop-rake

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false