name: CI
on:
  push:
jobs:
  build:
    runs-on: ${{matrix.os}}
    name: Ruby ${{ matrix.ruby }} @ ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: ['3.1', '3.2', jruby, truffleruby, '3.3', '3.4']
        exclude:
        - os: windows-latest
          ruby: truffleruby
        - os: windows-latest
          ruby: jruby
    steps:
    - uses: actions/checkout@v5
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake test
    - name: Run rubocop
      run: bundle exec rake rubocop
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') && github.repository == 'captn3m0/ruby-deb-version'}}
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    name: Release Gem
    needs: build
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - uses: rubygems/release-gem@v1
