name: CI
on:
  push:
jobs:
  build:
    runs-on: ${{matrix.os}}
    name: Ruby ${{ matrix.ruby }} @ ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: ['3.0', '3.1', '3.2', jruby, truffleruby]
        exclude:
        - os: windows-latest
          ruby: truffleruby
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake test
    - name: Run rubocop
      run: bundle exec rake rubocop